name: Add contributors
'on':
  workflow_run:
    workflows:
      - TOC Generator
    types:
      - completed
jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BobAnkh/add-contributors@master
        with:
          CONTRIBUTOR: '### Contributors'
          COLUMN_PER_ROW: '6'
          ACCESS_TOKEN: '${{secrets.ACCESS_TOKEN}}'
          IMG_WIDTH: '100'
          FONT_SIZE: '14'
          BRANCH: 'main'
          PULL_REQUEST: 'main'
          PATH: /README.md
          COMMIT_MESSAGE: 'docs(README): update contributors'
          AVATAR_SHAPE: round
